import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Module 1',
      link: {
        type: 'doc',
        id: 'module1/chapter1', // Link to the first chapter of Module 1
      },
      items: [{type: 'autogenerated', dirName: 'module1'}],
    },
    {
      type: 'category',
      label: 'Module 2',
      link: {
        type: 'doc',
        id: 'module2/chapter5', // Link to the first chapter of Module 2
      },
      items: [{type: 'autogenerated', dirName: 'module2'}],
    },
    {
      type: 'category',
      label: 'Module 3',
      link: {
        type: 'doc',
        id: 'module3/chapter9', // Link to the first chapter of Module 3
      },
      items: [{type: 'autogenerated', dirName: 'module3'}],
    },
    {
      type: 'category',
      label: 'Module 4',
      link: {
        type: 'doc',
        id: 'module4/chapter12', // Link to the first chapter of Module 4
      },
      items: [{type: 'autogenerated', dirName: 'module4'}],
    },
  ],
};

export default sidebars;
